image_res: 256
vision_width: 768
embed_dim: 256
batch_size_train: 24 
batch_size_test: 48
temp: 0.07
mlm_probability: 0.15
queue_size: 65536
momentum: 0.995
alpha: 0.4
warm_up: True

optimizer: {opt: adamW, lr: 1e-6, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-6, epochs: 40, min_lr: 1e-7, decay_rate: 1, warmup_lr: 1e-7, warmup_epochs: 20, cooldown_epochs: 0}